import Head from 'next/head'
import Features from '../components/home/Features'
import Hero from '../components/home/Hero'
import NavBar from '../components/home/NavBar'
import Layout from '../components/layouts/Layout'

export default function Home() {
  return (
		<Layout>
			<Head>
				<title>Artist Finder</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<Features />
		</Layout>
	);
}
